version: '3.1'

services:
  postgres:
    image: postgres:16.0-alpine3.17
    container_name: sflotify-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - sflotify-db_data:/var/lib/postgresql/data
volumes:
  sflotify-db_data:
